# Generated by Django 4.2.29 on 2026-04-07 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='nome',
            new_name='nome_convidado',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='slug_token',
        ),
        migrations.AddField(
            model_name='visitante',
            name='id_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='ReservaPiscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=15)),
                ('resposta_gestao', models.TextField(blank=True, null=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
