# Generated by Django 4.2.29 on 2026-04-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aviso_rename_nome_visitante_nome_convidado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='nome_convidado',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='id_acesso',
        ),
    ]
