# Generated by Django 4.2.29 on 2026-04-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_convidado_visitante_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Caixa da Amazon, Envelopes, etc.', max_length=200)),
                ('data_chegada', models.DateTimeField(auto_now_add=True)),
                ('entregue', models.BooleanField(default=False)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('morador', models.ForeignKey(limit_choices_to={'role': 'MORADOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
