# Generated by Django 4.2.29 on 2026-04-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_encomenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='balancetes/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('mes_referencia', models.DateField()),
            ],
        ),
    ]
