# Generated by Django 4.2.29 on 2026-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_balancete'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='horario_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
