# Generated by Django 4.2.29 on 2026-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_veiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('CARRO', '🚗 Carro'), ('MOTO', '🏍️ Moto')], default='CARRO', max_length=10),
        ),
    ]
