# Generated by Django 4.2.29 on 2026-04-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_veiculo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='data_chegada',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='data_recebimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='porteiro_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='retirado_por',
            field=models.CharField(blank=True, help_text='Nome de quem buscou', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição do Pacote'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='morador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
