# Generated by Django 4.2.29 on 2026-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_encomenda_data_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('RECEBIDO', 'Recebido pela Portaria'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=15),
        ),
    ]
