# Generated by Django 5.1.7 on 2026-04-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ocorrencia_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='horario_entrada',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='morador',
        ),
    ]
